### ISSUE TITLE
Trouble with compiling dataloader, google cloud datastore, appengine in go1.8

### ISSUE THREAD

**Issue by spife129** [graph-gophers/dataloader#40]
I am trying to use dataloader with my go application that runs on google's app engine. After I load the dataloader lib into my application, I got a number of errors from golang compiler. Any idea or tips on how to solve the issue? Thanks a lot!

dataloader.go:183: cannot use NewCache() (type *InMemoryCache) as type Cache in assignment:
	*InMemoryCache does not implement Cache (wrong type for Delete method)
		have Delete(context.Context, interface {}) bool
		want Delete(context.Context, Key) bool

inMemoryCache.go:24: cannot use items (type map[interface {}]Thunk) as type map[string]Thunk in field value
inMemoryCache.go:31: key.Key undefined (type Key has no field or method Key)
inMemoryCache.go:41: key.Key undefined (type Key has no field or method Key)
inMemoryCache.go:51: cannot use key (type interface {}) as type Key in argument to c.Get:
	interface {} does not implement Key (missing Raw method)
inMemoryCache.go:54: key.Key undefined (type interface {} is interface with no methods)

**Comment by spife129** [comment]
It seems the library only works with go1.9 as the key.key undefined issue is gone when I switched to go1.9

**Comment by nicksrandall** [comment]
We can probably fix this. I'm going to take a look. Thanks for reporting!

**Comment by nicksrandall** [comment]
This is now fixed for go versions < 1.9
